Add `validations.throwOnFailure` option
ivanvotti/ember-svg-jar pull request #167
Opened 2020-10-21 12:09 UTC by Turbo87

We would like our build to fail on CI when an SVG without a `viewBox` is submitted. This new option allows us to throw an error instead of printing the console warning.

/cc @ivanvotti

2020-11-11 09:47 UTC, Turbo87 commented
@ivanvotti any thoughts on this?

2020-11-11 17:24 UTC, ivanvotti requested changes
Sorry, I'm pretty busy recently. The feature makes sense. I'd suggest to clean up some Prettier side effects in the `configuration.md` also add this new option to:
- the default options with `false` as its value: https://github.com/ivanvotti/ember-svg-jar/blob/0cf6a725b50fe58a94e0df4ba5a7a2846466b2e1/lib/build-options.js#L71

- also to build options test: https://github.com/ivanvotti/ember-svg-jar/blob/2c8a93b1382212d7a103e19898d7c059ea8b254b/node-tests/unit/build-options-test.js#L169

- and to the default config doc: https://github.com/ivanvotti/ember-svg-jar/blob/20d4a650b306eeedc9f51d4696f10017bcac7dcb/docs/configuration.md#global-options

2020-11-11 17:24 UTC, ivanvotti commented on docs/configuration.md
> +    strategy: 'inline';
```suggestion
    strategy: 'inline',
```

2020-11-11 17:24 UTC, ivanvotti commented on docs/configuration.md
> +      plugins: [{ removeUselessStrokeAndFill: false }, { removeTitle: true }];
I guess it's Prettier
```suggestion
      plugins: [
        { removeUselessStrokeAndFill: false },
        { removeTitle: true },
      ]
```

2020-11-11 17:24 UTC, ivanvotti commented on docs/configuration.md
> +      validateViewBox: false;
```suggestion
      validateViewBox: false,
```

2020-11-11 17:27 UTC, Turbo87 commented
whoops, I totally missed all of these unrelated markdown changes 😱 

I've removed them for now to make this PR only focussed on the new flag :)

2020-11-12 14:36 UTC, Turbo87 commented
> the default options with false as its value

✅ 

> also to build options test:

✅ 

> and to the default config doc

should be in there already :)

2020-11-12 17:03 UTC, merged

2020-11-13 08:57 UTC, Turbo87 commented
thanks for merging!  🙏 

if there is any way I can help with getting this released let me know :)