Fix the vulnerabiltiy issue discussed in #197
ivanvotti/ember-svg-jar pull request #198
Opened 2021-08-15 13:24 UTC by evansrobert

Hi, @jherdman, this PR can fix the vulnerabiltiy issue we have discussed in #197. 
It can update `cheerio ^0.22.0 ➔ ^1.0.0-rc.4` to remove the  vulnerability [**CVE-2021-33587**](https://snyk.io/vuln/SNYK-JS-CSSWHAT-1298035) introduced by **css-what**, since **cheerio@1.0.0-rc.4**(>=1.0.0-rc.4) doesn’t depends on **css-what** any more.
It would be better if **ember-svg-jar@2.3./*** can fix this issue and release a patched version **ember-svg-jar@2.3.4** to npm.Then this vulnerbility patch can be automatically propagated into a large amount of downstream projects :)
Please check it.
Thanks again.

2021-08-16 13:35 UTC, jherdman requested changes
You'll also need to update `yarn.lock` by running `yarn`

2021-09-29 00:11 UTC, lskillington commented
Bump on this one @evansrobert 😅

2021-09-29 16:03 UTC, jherdman commented
@lskillington I'll try and crank this out today.

2021-10-01 20:38 UTC, jherdman commented
This pull request will require more work than is described here. I'll open a PR soon that addresses this concern. I'm going to close this one so as not to confuse the matter.

2021-10-01 20:38 UTC, closed without merging